[package]
name = "bark-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
bark-core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
terminal_size = "0.4"
directories = "5"
rusqlite = "0.31"
serde_json = "1"
toml = "0.8"
uuid = { version = "1", features = ["v4"] }

[[bin]]
name = "bark"
path = "src/main.rs"
